### ISSUE TITLE
Raspi Error on Start

### ISSUE THREAD

**Issue by focamonca** [InstaPy/instapy-wiki#34]
Everything went smooth, I created my quickstart.py but when I run python3 quickstart.py this is the output:

`pi@raspberrypi:~ $ python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    from instapy import InstaPy
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 33, in <module>
    from .clarifai_util import check_image
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/home/pi/.local/lib/python3.7/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/home/pi/.local/lib/python3.7/site-packages/clarifai/rest/client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "/home/pi/.local/lib/python3.7/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/home/pi/.local/lib/python3.7/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/pi/.local/lib/python3.7/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/pi/.local/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so)
`

can you please help?

**Comment by PropovedNik007** [comment]
Had the same problem on previous Raspbian on debian 10, try to install new Raspberry Pi OS. It based on Debian version: 11 (bullseye). Looks like such packages are not supported now. But then I have another problems with geckodriver.
