### ISSUE TITLE
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes'

### ISSUE THREAD

**Issue by codeclinic** [InstaPy/instapy-wiki#36]
If I run `python3 quickstart.py` InstaPy fails to run and returns the following trace:
(Debian Bullseye on Rpi4)
```
Traceback (most recent call last):
  File "/home/ha-server-pi/.local/lib/python3.9/site-packages/instapy/InstaPyScripts/quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/home/ha-server-pi/.local/lib/python3.9/site-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/ha-server-pi/.local/lib/python3.9/site-packages/instapy/instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "/home/ha-server-pi/.local/lib/python3.9/site-packages/instapy/browser.py", line 14, in <module>
    from .util import interruption_handler
  File "/home/ha-server-pi/.local/lib/python3.9/site-packages/instapy/util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (/home/ha-server-pi/.local/lib/python3.9/site-packages/emoji/unicode_codes/__init__.py)
```

If I  `pip3 install emoji` it says that "Requirement already satisfied: emoji in /home/ha-server-pi/.local/lib/python3.9/site-packages (2.0.0)"

**Comment by sqoshi** [comment]
#from emoji import UNICODE_EMOJI
import emoji

in isntapy/util.py

**Comment by sqoshi** [comment]
t ofix

**Comment by sachhu** [comment]
Any solution? I am still getting this issue

**Comment by delameter** [comment]
```
venv/bin/pip install "emoji<=1.7.0"
```

**Comment by delameter** [comment]
btw thats not the only failing dependency, at least on python 3.10. the second one is `clarifai`, downgrade it too if you encounter problems:
```
venv/bin/pip install "clarifai<9"
```
this should install clarifai 2.6.2

also these:
```shell
venv/bin/pip install "instapy-chromedriver==2.36.post0"
venv/bin/pip install "selenium<=4.9"
```

**Comment by delameter** [comment]
here is a setup which successfully runs on my system (ubuntu 20):

[requirements.txt](https://github.com/InstaPy/instapy-docs/files/12115958/requirements.txt)


logging in doesn't work though, but I'll fork the project and try to do smth about it

**Comment by ai9anya** [comment]
> here is a setup which successfully runs on my system (ubuntu 20):
> 
> [requirements.txt](https://github.com/InstaPy/instapy-docs/files/12115958/requirements.txt)
> 
> logging in doesn't work though, but I'll fork the project and try to do smth about it

WARNING [2023-07-26 11:39:57] [ ]  - Hide Selenium Extension: error
INFO [2023-07-26 11:40:02] [ ]  - Cookie file not found, creating cookie...
WARNING [2023-07-26 11:40:12] [ ]  Login A/B test detected! Trying another string...
WARNING [2023-07-26 11:40:17] [ ]  Could not pass the login A/B test. Trying last string...
ERROR [2023-07-26 11:40:22] [ ]  Login A/B test failed!

Everything stops at the login page. What can be done?
